SELECT *
FROM INFORMATION_SCHEMA.TABLE_PRIVILEGES
WHERE GRANTEE NOT LIKE '\'root\'@\'localhost\'';

SELECT *
FROM INFORMATION_SCHEMA.USER_PRIVILEGES
WHERE GRANTEE NOT LIKE '\'root\'@\'localhost\'';

SELECT *
FROM INFORMATION_SCHEMA.COLUMN_PRIVILEGES
WHERE GRANTEE NOT LIKE '\'root\'@\'localhost\'';

SHOW GRANTS FOR 'gestor'@'localhost';
SHOW GRANTS FOR 'secretario'@'localhost';
SHOW GRANTS FOR 'comercial'@'localhost';